{% set version = "0.31" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pkgmaker
  version: {{ version|replace("-", "_") }}

source:
  fn: pkgmaker_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/pkgmaker_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pkgmaker/pkgmaker_{{ version }}.tar.gz
  sha256: cb12a54889f14d4d05d8fba890ffc7c981db301f81fb7fe6819c777ea7d98631

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-bibtex >=0.4
    - r-codetools
    - r-digest
    - r-magrittr
    - r-registry
    - r-stringi
    - r-stringr
    - r-withr
    - r-xtable
  run:
    - r-base
    - r-bibtex >=0.4
    - r-codetools
    - r-digest
    - r-magrittr
    - r-registry
    - r-stringi
    - r-stringr
    - r-withr
    - r-xtable

test:
  commands:
    - $R -e "library('pkgmaker')"           # [not win]
    - "\"%R%\" -e \"library('pkgmaker')\""  # [win]

about:
  home: https://renozao.github.io/pkgmaker
  license: GPL (>= 2)
  summary: Provides some low-level utilities to use for package development. It currently provides
    managers for multiple package specific options and registries, vignette, unit test
    and bibtex related utilities. It serves as a base package for packages like NMF,
    RcppOctave, doRNG, and as an incubator package for other general purposes utilities,
    that will eventually be packaged separately. It is still under heavy development
    and changes in the interface(s) are more than likely to happen.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
