# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KnWkJsuGr+/9DB2pDig4NwmPRsVeAYc9x9i8TtMhd+khl/ILAgB3jfO5g7v3aDINImXBLXwN60J/0JuqwxDH8vY9Wmggg3Ki87EKlHCIzb6FyhiLYsfWm9atyHri1LiAtH6jDRM7c1o2HiAjqvwCnedf7cEJYhqDvT40O5Xs40sb8GV461u5klTpmOKlvZqFDgWBR2IZD1GTxKTrFxKwNFGg0CORccVNhn1PEzWPnskpCVDRuDZf8A+hx0gt3H629Kaih/P1h14ytx6RrpLr1c9cFiw7NJFJKunu28p+huE4gRlFgPntlcP/78DLVn7y3desXcgNfzr48Qx+hTEaSEpfEt1ZrkRUzldkQiEVIKvN/PkMh+81QRtAli5QETnVR/fMuS44DcAn/rrzDdzRbwUi7eE0a8wJ1FWYarGHSojJOE5+/8tuKM/LiMIzOqKxjoORCdn7EU2jI5pdfUYrKJ2aAT11+MYSrMFAluZoy6JXJU+C98nFTIW0anvvqzIPhLoVR37R7dx/gsNdCzRlmcU8HFH26uC+Mf5dnS1WO2h+wmYsomyI/1k6ODXDGKyF3K9znGvyyEojtt+uqEKUvstskDU9EefRarl3DNiYnUK71aYyP4dnxSqifhZPXwY9kePeKIIInbC9Av8F4iPrXwR4uCZklabd2yY9Kw6n1Lg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
