appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: KnWkJsuGr+/9DB2pDig4NwmPRsVeAYc9x9i8TtMhd+khl/ILAgB3jfO5g7v3aDINImXBLXwN60J/0JuqwxDH8vY9Wmggg3Ki87EKlHCIzb6FyhiLYsfWm9atyHri1LiAtH6jDRM7c1o2HiAjqvwCnedf7cEJYhqDvT40O5Xs40sb8GV461u5klTpmOKlvZqFDgWBR2IZD1GTxKTrFxKwNFGg0CORccVNhn1PEzWPnskpCVDRuDZf8A+hx0gt3H629Kaih/P1h14ytx6RrpLr1c9cFiw7NJFJKunu28p+huE4gRlFgPntlcP/78DLVn7y3desXcgNfzr48Qx+hTEaSEpfEt1ZrkRUzldkQiEVIKvN/PkMh+81QRtAli5QETnVR/fMuS44DcAn/rrzDdzRbwUi7eE0a8wJ1FWYarGHSojJOE5+/8tuKM/LiMIzOqKxjoORCdn7EU2jI5pdfUYrKJ2aAT11+MYSrMFAluZoy6JXJU+C98nFTIW0anvvqzIPhLoVR37R7dx/gsNdCzRlmcU8HFH26uC+Mf5dnS1WO2h+wmYsomyI/1k6ODXDGKyF3K9znGvyyEojtt+uqEKUvstskDU9EefRarl3DNiYnUK71aYyP4dnxSqifhZPXwY9kePeKIIInbC9Av8F4iPrXwR4uCZklabd2yY9Kw6n1Lg=}
bot:
  automerge: true
